<?php


$configArray = [
    'LANGUAGE'          => 'en-us',
    'TITLE'             => 'Saguaro Imageboard!',
    'SUBTITLE'          => 'No artificial sweeteners!',
    'META_DESCRIPTION'  => 'An imageboard powered by saguaro',
    'NSFW'              => false,
    'SHOW_BANNERS'      => false,
    'SHOW_TITLE'        => true,
    'USE_BBCODE'       => false,
    'DISPLAY_ID'        => false,
    'POSTLENGTH'        => 3000,
    'FORCED_ANON'       => false,
    'DICE_ROLL'         => false,
    'COUNTRY_FLAGS'     => false,
    'FORTUNE_TRIP'      => false,
    'NOPICBOX'          => false,
    'BOTCHECK'          => false,
    'RECAPTCHA'         => false,
    'DUPE_CHECK'        => false,
    'THREADS_PER_PAGE'  => 10,
    'PAGES_PER_BOARD'   => 10,
    'COOLDOWN_POST'     => 10,
    'COOLDOWN_THREAD'   => 60,
    'COOLDOWN_FILE'     => 15,
    'MAX_RES'           => 500,
    'MAX_IMGRES'        => 250,
    'MAX_KB'            => 2048,
    'MAX_FILE_COUNT'    => 1,
    'MAX_LINES'        => 50,
    'MAX_LINES_SHOWN'   => 25,
    'ALLOW_TEXTONLY'    => false,
    'ALLOW_WEBMS'       => false,
    'ALLOW_AUDIO'       => false,
    'MAX_DURATION'      => 60,
    'MAX_W'             => 250,
    'MAX_H'             => 250,
    'MAXR_W'            => 125,
    'MAXR_H'            => 125,
    'MIN_W'             => 30,
    'MIN_H'             => 30
];